// Données mock pour le développement
import type { Product, Category, User } from '@/lib/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Zen Buddha Bowl',
    description: 'Quinoa, avocat, pois chiches, légumes de saison',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=520&h=360&fit=crop',
    category: 'nourrir',
    rating: 4.8,
    kcal: 520,
    prepTime: 15,
    tags: ['Vegan', 'Bio'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: true,
    orderedToday: 32,
  },
  {
    id: '2',
    name: 'Matcha Zen Latte Glacé',
    description: "Thé matcha de cérémonie, lait d'avoine, sirop d'érable bio",
    price: 650,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400&h=520&fit=crop',
    category: 'savourer',
    rating: 4.8,
    kcal: 580,
    prepTime: 15,
    tags: ['Vegan', 'Bio'],
    location: 'Franconville',
    available: true,
    isNew: true,
    isSeasonal: false,
    isPopular: true,
    orderedToday: 47,
  },
  {
    id: '3',
    name: 'Salade Printanière',
    description: 'Mesclun, chèvre frais, noix, vinaigrette miel',
    price: 1290,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=520&h=360&fit=crop',
    category: 'nourrir',
    rating: 4.6,
    kcal: 380,
    prepTime: 10,
    tags: ['Bio'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: true,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '4',
    name: 'Earl Grey Bio',
    description: 'Thé noir bergamote, notes florales délicates',
    price: 480,
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=500&fit=crop',
    category: 'savourer',
    rating: 4.5,
    kcal: 0,
    prepTime: 5,
    tags: ['Bio'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '5',
    name: 'Smoothie Vert Détox',
    description: 'Épinards, pomme, gingembre, citron',
    price: 650,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400&h=400&fit=crop',
    category: 'savourer',
    rating: 4.7,
    kcal: 180,
    prepTime: 5,
    tags: ['Vegan', 'Bio'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '6',
    name: 'Sencha Japon',
    description: 'Thé vert japonais, notes végétales fraîches',
    price: 450,
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400&h=500&fit=crop',
    category: 'savourer',
    rating: 4.4,
    kcal: 0,
    prepTime: 5,
    tags: ['Bio'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '7',
    name: 'Carrot Cake Maison',
    description: 'Gâteau aux carottes, noix de pécan, glaçage cream cheese, cannelle',
    price: 590,
    image: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=520&h=360&fit=crop',
    category: 'patisseries',
    rating: 4.9,
    kcal: 340,
    prepTime: 0,
    tags: ['Fait maison'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '8',
    name: 'Cookie Chocolat Noir',
    description: 'Cookie moelleux au chocolat noir 70%, pépites caramélisées',
    price: 390,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=520&h=360&fit=crop',
    category: 'patisseries',
    rating: 4.7,
    kcal: 280,
    prepTime: 0,
    tags: ['Fait maison'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '9',
    name: 'Banana Bread Vegan',
    description: 'Banana bread aux noix, sans beurre ni œufs, douceur naturelle',
    price: 490,
    image: 'https://images.unsplash.com/photo-1605090930601-71c4b981c2ac?w=520&h=360&fit=crop',
    category: 'patisseries',
    rating: 4.6,
    kcal: 260,
    prepTime: 0,
    tags: ['Vegan', 'Fait maison'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '10',
    name: 'Wrap Avocat Poulet',
    description: 'Tortilla complète, poulet rôti, avocat, crudités, sauce yaourt',
    price: 1090,
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=520&h=360&fit=crop',
    category: 'emporter',
    rating: 4.5,
    kcal: 480,
    prepTime: 8,
    tags: ['Fait maison'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
  {
    id: '11',
    name: 'Poke Bowl Saumon',
    description: 'Riz vinaigré, saumon mariné, edamame, avocat, mangue, sésame',
    price: 1590,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=520&h=360&fit=crop',
    category: 'emporter',
    rating: 4.8,
    kcal: 550,
    prepTime: 12,
    tags: ['Frais'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: true,
    isPopular: true,
    orderedToday: 28,
  },
  {
    id: '12',
    name: 'Granola Bowl',
    description: 'Granola maison, yaourt grec, fruits frais de saison, miel bio',
    price: 850,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=520&h=360&fit=crop',
    category: 'nourrir',
    rating: 4.6,
    kcal: 420,
    prepTime: 5,
    tags: ['Bio', 'Fait maison'],
    location: 'Franconville',
    available: true,
    isNew: false,
    isSeasonal: false,
    isPopular: false,
    orderedToday: 0,
  },
];

export const mockCategories: Category[] = [
  { id: 'all', label: 'Tout' },
  { id: 'nourrir', label: 'Nourrir' },
  { id: 'savourer', label: 'Savourer' },
  { id: 'patisseries', label: 'Pâtisseries' },
  { id: 'emporter', label: 'Emporter' },
];

export const mockUser: User = {
  id: 'mock-user-001',
  fullName: 'Johan',
  phone: '+33612345678',
  email: 'johan@teaven.fr',
  dietaryPreferences: ['Bio'],
  loyaltyPoints: 1250,
  loyaltyLevel: 'Or',
  walletBalance: 4250,
  createdAt: '2025-01-15T10:00:00Z',
  updatedAt: '2026-03-19T12:00:00Z',
};
