// Données mock pour le développement
import type { Product, Category, User } from '@/lib/types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Zen Buddha Bowl',
    description: 'Quinoa, avocat, pois chiches, légumes de saison',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=520&h=360&fit=crop',
    category: 'nourrir',
    rating: 4.8,
    kcal: 520,
    prepTime: 15,
    tags: ['Vegan', 'Bio'],
    location: 'Franconville',
    available: true,
  },
  {
    id: '2',
    name: 'Matcha Zen Latte Glacé',
    description: "Thé matcha de cérémonie, lait d'avoine, sirop d'érable bio",
    price: 650,
    image: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=400&h=520&fit=crop',
    category: 'savourer',
    rating: 4.8,
    kcal: 580,
    prepTime: 15,
    tags: ['Vegan', 'Bio'],
    location: 'Franconville',
    available: true,
  },
  {
    id: '3',
    name: 'Salade Printanière',
    description: 'Mesclun, chèvre frais, noix, vinaigrette miel',
    price: 1290,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=520&h=360&fit=crop',
    category: 'nourrir',
    rating: 4.6,
    kcal: 380,
    prepTime: 10,
    tags: ['Bio'],
    location: 'Franconville',
    available: true,
  },
  {
    id: '4',
    name: 'Earl Grey Bio',
    description: 'Thé noir bergamote, notes florales délicates',
    price: 480,
    image: 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=400&h=500&fit=crop',
    category: 'savourer',
    rating: 4.5,
    kcal: 0,
    prepTime: 5,
    tags: ['Bio'],
    location: 'Franconville',
    available: true,
  },
  {
    id: '5',
    name: 'Smoothie Vert Détox',
    description: 'Épinards, pomme, gingembre, citron',
    price: 650,
    image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400&h=400&fit=crop',
    category: 'savourer',
    rating: 4.7,
    kcal: 180,
    prepTime: 5,
    tags: ['Vegan', 'Bio'],
    location: 'Franconville',
    available: true,
  },
  {
    id: '6',
    name: 'Sencha Japon',
    description: 'Thé vert japonais, notes végétales fraîches',
    price: 450,
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400&h=500&fit=crop',
    category: 'savourer',
    rating: 4.4,
    kcal: 0,
    prepTime: 5,
    tags: ['Bio'],
    location: 'Franconville',
    available: true,
  },
];

export const mockCategories: Category[] = [
  { id: 'all', label: 'Tout' },
  { id: 'nourrir', label: 'Nourrir' },
  { id: 'savourer', label: 'Savourer' },
  { id: 'emporter', label: 'Emporter' },
];

export const mockUser: Omit<User, 'id'> = {
  name: 'Johan',
  phone: '+33612345678',
  loyaltyPoints: 1250,
  loyaltyLevel: 'Or',
  walletBalance: 4250,
};
